<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
		<TargetFrameworks>net8.0-android</TargetFrameworks>
		<!--<TargetFrameworks>net8.0-android;net8.0-ios</TargetFrameworks>
        <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net8.0-windows10.0.19041.0</TargetFrameworks>-->
        <!-- Uncomment to also build the tizen app. You will need to install tizen by following this: https://github.com/Samsung/Tizen.NET -->
        <!-- <TargetFrameworks>$(TargetFrameworks);net8.0-tizen</TargetFrameworks> -->

        <!-- Note for MacCatalyst:
        The default runtime is maccatalyst-x64, except in Release config, in which case the default is maccatalyst-x64;maccatalyst-arm64.
        When specifying both architectures, use the plural <RuntimeIdentifiers> instead of the singular <RuntimeIdentifier>.
        The Mac App Store will NOT accept apps with ONLY maccatalyst-arm64 indicated;
        either BOTH runtimes must be indicated or ONLY macatalyst-x64. -->
        <!-- For example: <RuntimeIdentifiers>maccatalyst-x64;maccatalyst-arm64</RuntimeIdentifiers> -->

        <OutputType>Exe</OutputType>
        <RootNamespace>PassingCar</RootNamespace>
        <UseMaui>true</UseMaui>
        <SingleProject>true</SingleProject>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <!-- Display name -->
        <ApplicationTitle>PassingCar</ApplicationTitle>

        <!-- App Identifier -->
        <ApplicationId>com.companyname.passingcar</ApplicationId>

        <!-- Versions -->
        <ApplicationDisplayVersion>2</ApplicationDisplayVersion>
        <ApplicationVersion>2</ApplicationVersion>

        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">11.0</SupportedOSPlatformVersion>
        <SupportedOSPlatformVersion>11.0</SupportedOSPlatformVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
        <TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>
        <!--<Version>1.0.1</Version>-->
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0-android|AnyCPU'">
      <AndroidPackageFormat>apk</AndroidPackageFormat>
      <RunAOTCompilation>False</RunAOTCompilation>
      <PublishTrimmed>False</PublishTrimmed>
    </PropertyGroup>
    
    <!--<PropertyGroup Condition="$(TargetFramework.Contains('-android')) and '$(Configuration)' == 'Release'">     
        <PublishTrimmed>False</PublishTrimmed>     
        <EnableTrimAnalyzer>False</EnableTrimAnalyzer>    
        <RunAOTCompilation>False</RunAOTCompilation>   
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <AndroidUseSharedRuntime>true</AndroidUseSharedRuntime>
      <AndroidEnableMultiDex>false</AndroidEnableMultiDex>
      <CodesignKey>iPhone Distribution: Beniamin Nicolae Suiugan (N7FUS4WRS7)</CodesignKey>
      <CodesignProvision>PassingCar</CodesignProvision>
      <MtouchLink>SdkOnly</MtouchLink>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <CodesignKey>iPhone Distribution: Beniamin Nicolae Suiugan (N7FUS4WRS7)</CodesignKey>
      <CodesignProvision>PassingCar</CodesignProvision>
    </PropertyGroup>-->
	  <ItemGroup>
        <!-- App Icon -->
        <MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#1892df" />

        <!-- Splash Screen -->
        <MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#1892df" BaseSize="128,128" />

        <!-- Images -->
        <MauiImage Include="Resources\Images\*" />
        <MauiImage Update="Resources\Images\dotnet_bot.png" Resize="True" BaseSize="300,185" />

        <!-- Custom Fonts -->
        <MauiFont Include="Resources\Fonts\*" />

        <!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
        <MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
    </ItemGroup>
    <Target Name="DoNotLinkWithBrowserEngineKit" AfterTargets="_ComputeLinkNativeExecutableInputs">
        <ItemGroup>
            <_NativeExecutableFrameworks Remove="BrowserEngineKit" />
        </ItemGroup>
    </Target>
    <ItemGroup>
        <PackageReference Include="Auth0.OidcClient.MAUI" Version="1.0.1" />
        <PackageReference Include="CommunityToolkit.Maui" Version="9.1.0" />
        <PackageReference Include="Dapper.Contrib.Extensions.Tablename" Version="1.1.1" />
        <PackageReference Include="dotMorten.MauiEx" Version="1.0.0-preview1" />
        <PackageReference Include="FFImageLoadingCompat.Svg.Maui" Version="0.1.1" />
        <PackageReference Include="HarfBuzzSharp" Version="7.3.0.2" />
        <PackageReference Include="libphonenumber-csharp" Version="8.13.46" />
        <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="8.0.10" />
        <PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="8.1.2" />
        <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.1.2" />
        <PackageReference Include="Microsoft.Maui.Controls" Version="8.0.91" />
        <PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="8.0.91" />
        <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.0" />
        <PackageReference Include="Microsoft.Maui.Controls.Maps" Version="8.0.91" />
        <PackageReference Include="Mopups" Version="1.3.2" />
        <PackageReference Include="Mopups.Maui" Version="1.0.0" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
        <PackageReference Include="PancakeView.Maui" Version="8.0.0" />
        <PackageReference Include="RestSharp" Version="112.1.0" />
        <PackageReference Include="SkiaSharp" Version="2.88.8" />
        <PackageReference Include="SkiaSharp.Views.Maui.Controls" Version="2.88.8" />
        <PackageReference Include="SkiaSharp.Views.Maui.Controls.Compatibility" Version="2.88.8" />
		<PackageReference Include="SkiaSharp.Views.Maui.Core" Version="2.88.8" />
		<PackageReference Include="sqlite-net-pcl" Version="1.9.172" />
		<PackageReference Include="Stripe.net" Version="42.2.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.1.2" />
    </ItemGroup>



    <ItemGroup>
      <MauiXaml Update="Views\Register\SetNewPassword.xaml">
        <Generator>MSBuild:Compile</Generator>
      </MauiXaml>
    </ItemGroup>

</Project>
